# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='opere/images')),
                ('location', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Foti',
            },
        ),
    ]
