# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('opera_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='opere.Opera')),
                ('location', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Foti',
            },
            bases=('opere.opera',),
        ),
    ]
