# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opera',
            old_name='image',
            new_name='image_color',
        ),
        migrations.AddField(
            model_name='opera',
            name='image_grayscale',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
