# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0002_auto_20160228_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opera',
            name='image_grayscale',
        ),
    ]
