# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0003_remove_opera_image_grayscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='is_foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opera',
            name='is_scritto',
            field=models.BooleanField(default=False),
        ),
    ]
