# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0004_auto_20160229_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opera',
            options={'ordering': ('opera_position',), 'verbose_name_plural': 'Opere'},
        ),
        migrations.AddField(
            model_name='opera',
            name='opera_position',
            field=models.IntegerField(default=0),
        ),
    ]
