# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0005_auto_20160229_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opera',
            options={'ordering': ('opera_index',), 'verbose_name_plural': 'Opere'},
        ),
        migrations.RenameField(
            model_name='opera',
            old_name='opera_position',
            new_name='opera_index',
        ),
    ]
