# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 17:38
from __future__ import unicode_literals

from django.db import migrations

from opere.models import Opera


def set_initial_opera_ordering(apps, schema_editor):
    order = 0
    for opera in Opera.objects.all():
        order += 1
        opera.opera_index = order
        opera.save()


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0006_auto_20160229_1737'),
    ]

    operations = [
        migrations.RunPython(set_initial_opera_ordering, reverse_code=migrations.RunPython.noop),
    ]
