# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scritti', '0002_auto_20160229_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scritto',
            options={'ordering': ('scritto_index',), 'verbose_name_plural': 'Scritti'},
        ),
        migrations.RenameField(
            model_name='scritto',
            old_name='scritto_order',
            new_name='scritto_index',
        ),
    ]
