# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('_title', models.CharField(blank=True, help_text="Site title used in tab. Defaults to 'name' if left blank.", max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Just a quick description (e.g. "Waddling through the world in search of adventure and snuggles" to go with "Nomad Penguin"', max_length=515)),
                ('intro', models.TextField(blank=True, max_length=1024)),
                ('bio_title', models.CharField(blank=True, max_length=64)),
                ('bio', models.TextField(blank=True, max_length=4096)),
                ('_contact_name', models.CharField(blank=True, help_text="Just in case you didn't use your real name up above. You can leave this blank if you want.", max_length=64)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(blank=True, help_text='"Postal Code", technically.', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True, help_text='In case you have another one, I guess?')),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('pinterest', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
