# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_auto_20160229_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='homepage_features',
            field=models.ManyToManyField(blank=True, help_text='Max of 6!', related_name='facade_homepage_features', to='opere.Opera'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_features',
            field=models.ManyToManyField(blank=True, help_text='Max of 6!', related_name='facade_photo_features', to='foti.Foto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='writing_features',
            field=models.ManyToManyField(blank=True, help_text='Max of 6!', related_name='facade_writing_features', to='scritti.Scritto'),
        ),
    ]
