# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scritti', '0004_initial_ordering'),
        ('facade', '0003_auto_20160229_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_homepage_features',
            field=models.ManyToManyField(blank=True, help_text='Max of 6!', related_name='facade_homepage_features', to='scritti.Scritto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='homepage_features',
            field=models.ManyToManyField(blank=True, help_text='Max of 6!', related_name='facade_old_homepage_features', to='opere.Opera'),
        ),
    ]
