# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 19:41
from __future__ import unicode_literals

from django.db import migrations


def move_homepage_features_from_opere_to_scritti(apps, schema_editor):
    Scritto = apps.get_model('scritti', 'Scritto')
    Profile = apps.get_model('facade', 'Profile')

    profile = Profile.objects.first()

    for opera in profile.homepage_features.all():
        scritto = Scritto.objects.get(name=opera.name)
        profile.new_homepage_features.add(scritto)

    profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_auto_20160229_1938'),
    ]

    operations = [
        migrations.RunPython(move_homepage_features_from_opere_to_scritti, reverse_code=migrations.RunPython.noop),
    ]
