# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_auto_20160229_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_homepage_features',
        ),
    ]
