# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0008_profile_bio_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio_photo',
            new_name='bio_image',
        ),
    ]
