# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0010_auto_20160305_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tumblr',
            field=models.URLField(blank=True),
        ),
    ]
